name: Auto ETL to Supabase

on:
  schedule:
    - cron: "0 2 * * 1"  # ogni lunedì alle 2:00 UTC
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

        - name: Run ETL CO2
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python etl/etl_co2.py

      - name: Run ETL Temperature
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python etl/etl_temperature.py

      - name: Run ETL Sea Level
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python etl/etl_sea_level.py
